version: "3.9"
services:
  db:
    image: docker.io/library/postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  back:
    container_name: apollo-api

    build:
      context: .
      dockerfile: Dockerfile

    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres?schema=public
      PORT: 4000

    ports:
      - "8080:4000"
    depends_on:
      - db

volumes:
  db_data:
    driver: local
